{{/*
Service - Expose deployment ke network
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genieacs-relay.fullname" . }}
  labels:
    {{- include "genieacs-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "genieacs-relay.selectorLabels" . | nindent 4 }}
